import { getProviders, getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
        {/* Widgets */}

        {/* Modal */}
      </main>
    </div>
  )
}

// export async function getServerSideProps(context){
//   const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
//     (res) => res.json()
//   );
//   const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
//     (res) => res.json()
//   );
//   const providers = await getProviders();
//   const session = await getSession(context);

//   return {
//     props: {
//       trendingResults,
//       followResults,
//       providers,
//       session,
//     },
//   };
// }